services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
      - DEBUG=True
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    networks:
      - ea-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - ea-network

networks:
  ea-network:
    driver: bridge

volumes:
  data:
